SOLVER:
  MAX_ITER: 500000
  TYPE: Adam
  BASE_LR: 0.00005
  GAMMA: 0.1
  STEPS: [0]
  EPOCHS: [0]
DEBUG: False
DEBUG_W_GT: False
LOGDIR: ''
DEVICE: cuda
# NUM_WORKERS: 8
SEED_VALUE: -1
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  HF_KP_2D_W: 1000.0
  HF_KP_3D_W: 1000.0
  GL_HF_KP_2D_W: 30.
  FEET_KP_2D_W: 0.
  SHAPE_W: 0.06
  POSE_W: 60.0
  VERT_W: 0.0
  VERT_REG_W: 300.0
  INDEX_WEIGHTS: 2.0
  # Loss weights for surface parts. (24 Parts)
  PART_WEIGHTS: 0.3
  # Loss weights for UV regression.
  POINT_REGRESSION_WEIGHTS: 0.5
TRAIN:
  NUM_WORKERS: 8
  BATCH_SIZE: 64
  LOG_FERQ: 100
  SHUFFLE: True
  PIN_MEMORY: True
  USE_EFT: True
  USE_GT_CAM: False
  USE_ZERO_POSE: False
  HF_LOSS_ON: True
  BHF_MODE: 'full_body'
  FREEZE_ENCODER: ''
  FREEZE_PART: ''
  PW3D_RATIO: 0.2
  HR_IMG: False
  HF_ROOT_ALIGN: True
  USE_CONTOUR_2DLMK: True
TEST:
  BATCH_SIZE: 32
DATA:
  RESCALE_B: 1.
  RESCALE_H: 1.2
  RESCALE_F: 1.4
MODEL:
  # IWP, Identity rotation and Weak Perspective Camera
  USE_IWP_CAM: True
  USE_GT_FL: False
  PRED_PITCH: False
  MESH_MODEL: 'smplx'
  MESH_V2020: True
  N_BETAS_B: 10
  N_BETAS_H: 10
  N_BETAS_F: 100
  N_EXP: 50
  FACE_DENSE_SAM: True
  ADD_GENDER: False
  VPOSER_ON: False
  HAND_PCA_ON: False
  ALL_GENDER: False
  PyMAF:
    BACKBONE: 'hr48'
    HF_BACKBONE: 'res50'
    MAF_ON: True
    MLP_DIM: [256, 128, 64, 5]
    HF_MLP_DIM: [256, 128, 64, 5]
    MLP_VT_DIM: [256, 128, 64, 3]
    N_ITER: 3
    SUPV_LAST: False
    AUX_SUPV_ON: True
    HF_AUX_SUPV_ON: False
    HF_BOX_ALIGN: False
    DP_HEATMAP_SIZE: 56
    SEG_ON: False
    SEG_LAST: False
    GRID_FEAT: False
    USE_CAM_FEAT: True
    HF_IMG_SIZE: 224
    ADD_GRID: False
    OPT_WRIST: True     # correct wrist rotation
    ADAPT_INTEGR: True
    PRED_VIS_H: True
    HAND_VIS_TH: 0.1     # visible threshold for correcting wrist rotation
    OPT_HEAD: False      # correct head rotation
    HEAD_VIS_TH: 0.5     # visible threshold for correcting head rotation
    GRID_ALIGN:
      USE_ATT: True
      USE_FC: False
      ATT_FEAT_IDX: 2
      ATT_HEAD: 1
      ATT_STARTS: 1
RES_MODEL:
  DECONV_WITH_BIAS: False
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_DECONV_KERNELS:
  - 4
  - 4
  - 4
POSE_RES_MODEL:
  INIT_WEIGHTS: True
  NAME: 'pose_resnet'
  PRETR_SET: 'imagenet'   # 'none' 'imagenet' 'coco'
  # PRETRAINED: 'data/pretrained_model/resnet50-19c8e357.pth'
  PRETRAINED_IM: 'data/pretrained_model/resnet50-19c8e357.pth'
  PRETRAINED_COCO: 'data/pretrained_model/pose_resnet_50_256x192.pth.tar'
  EXTRA:
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 48
    - 64
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: False
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 50
HR_MODEL:
  INIT_WEIGHTS: True
  NAME: pose_hrnet
  PRETR_SET: 'coco'   # 'none' 'imagenet' 'coco'
  PRETRAINED_IM: 'data/pretrained_model/hrnet_w48-imgnet-8ef0771d.pth'
  PRETRAINED_COCO: 'data/pretrained_model/pose_hrnet_w48_256x192.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 256
  - 256
  HEATMAP_SIZE:
  - 64
  - 64
  SIGMA: 2
  EXTRA:
    PRETRAINED_LAYERS:
    - 'conv1'
    - 'bn1'
    - 'conv2'
    - 'bn2'
    - 'layer1'
    - 'transition1'
    - 'stage2'
    - 'transition2'
    - 'stage3'
    - 'transition3'
    - 'stage4'
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
